version: '3.8'
name: 'electric_ai_chat_dev'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ai-chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
    volumes:
      - ./postgres.conf:/etc/postgresql.conf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/00_shared_init.sql:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
