/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AiChatBackend": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "AiChatFrontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "AiChatSyncService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "AiChatVpc": {
      "type": "sst.aws.Vpc"
    }
    "NeonProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}