name: Deploy production stack

on:
  push:
    branches: ['main']

concurrency:
  group: prod-deploy-group

jobs:
  deploy-production:
    name: Deploy production stack
    environment: SST Deployments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm -r build

      - name: Cache SST state
        uses: actions/cache@v4
        with:
          path: .sst
          key: sst-cache-main-${{ runner.os }}
          restore-keys: |
            sst-cache-main-${{ runner.os }}

      - name: Deploy production stack
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
        run: |
          pnpm sst deploy --stage production
